# Generated by Django 4.2 on 2023-05-05 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.generate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile')),
                ('code', models.CharField(default=utils.generate.generate_code, max_length=8)),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('region', models.CharField(max_length=20, verbose_name='region')),
                ('street', models.CharField(max_length=20, verbose_name='street')),
                ('apartment', models.CharField(max_length=20, verbose_name='apartment')),
                ('Postcode_ZIP', models.CharField(max_length=20, verbose_name='Postcode_ZIP')),
                ('notes', models.CharField(max_length=200, verbose_name='notes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
