# Generated by Django 4.2 on 2023-05-05 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('image', models.ImageField(upload_to='post', verbose_name='image')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('head_topic', models.CharField(max_length=300, verbose_name='head_topic')),
                ('post', models.TextField(max_length=2500, verbose_name='post')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('Tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_author', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_department', to='food.department', verbose_name='department')),
            ],
        ),
    ]
